#!/usr/bin/env ProcessAnaTuples
#Models commonly used in MINERvA results

MnvGENIEv1: &MnvGENIEv1
  Flux: !FluxAndCV
  GENIE: !GENIE
  MINOSEfficiency: !MINOSEfficiency
  RPASuppression: !RPA
  Valencia2p2h: !2p2h
  NonResPiSuppression: !NonResPiSuppression

ForgotToReweight: &ForgotToReweight

#TODO: Is there a better name for this?
DefaultGENIE: &DefaultGENIE
  Flux: !FluxAndCV
  GENIE: !GENIE
  MINOSEfficiency: !MINOSEfficiency
