#File: Cuts.yaml
#Brief: Define common cuts I use in the NucCCNeutrons analysis.
#       It's up to the user to write another YAML file that uses
#       these cuts.
#Author: Andrew Olivier aolivier@ur.rochester.edu

#Kinematic and quality cuts inherited from the MEC analysis.
#MECMuonKinematics: &MECMuonKinematics !MuonKinematics
MaxMuonAngle: 20 #degrees
  MinMuonMomentum: 1500 #MeV
  MinNeutrinoE: 2000 #MeV

MECMinosMatch: &MECMinosMatch !MinosTime
  MinTime: -40 #ns
  MaxTime: 110 #ns

IsAntineutrino: &IsAntineutrino !Helicity
  Helicity: 2 #antineutrino via a MINERvA framework typedef

IsNeutrino: &IsNeutrino !Helicity
  Helicity: 1 #neutrino via a MINERvA framework typedef

LowQ3: &LowQ3 !Q3Range
  min: 0
  max: 0.4

OneTrack: &OneTrack !NTracks
  max: 1

#TODO: Am I still going to use these?
#Categorize neutron candidates by what FS particle produced them
GENIENeutrons: &GENIENeutrons !FSPDGCodes
  PDGs: [2112]

GeantNeutrons: &GeantNeutrons !IsNeutronFromGeant

EMAndHadrons: &EMAndHadrons !FSPDGCodes
  PDGs: [211, -211, 2212, 111, -111, 311, -311, 22]

Muon: &Muon !FSPDGCodes
  PDGs: [13, -13]
