#!/usr/bin/env ProcessAnaTuples
#File: InclusivePzPT.yaml
#Brief: Reproduces Dan's Medium Energy port of Amy's Low Energy 2D
#       inclusive cross section in muon momentum components.  If I get
#       roughly the same answers, my event loop can't be too bad, right?
#Author: Andrew Olivier aolivier@ur.rochester.edu

model: *MnvGENIEv1

app:
  useNuEConstraint: false
  nFluxUniverses: 50

systematics: []

signal: !EAvailableResolution
  name: "EAvailable"
  variable:
  binning: [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.26, 0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.4, 0.42, 0.44, 0.46, 0.48, 0.5, 0.52, 0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88, 0.9, 0.92, 0.94, 0.96, 0.98, 1]

cuts:
  truth:
    phaseSpace:
      Apothem: !Apothem
        apothem: !mm 850
      Tracker: *OneTrackTracker
      MuonMomentum: !MuonMomentum
        min: !GeV 2
      TrackAngle: !TrackAngle
        max: !degrees 20
      LowEAvailable: !EAvailRange
        min: &smallNegativeNumber !GeV -1e-3
        max: &maxEAvail !GeV 0.1
    signal:
      Antineutrino: !IsAntineutrino
      CC: !IsCC
  reco:
    Apothem: !Apothem
      apothem: !mm 850
    Tracker: *OneTrackTracker
    LowEAvailable: !RecoilERange
        min: *smallNegativeNumber
        max: *maxEAvail
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: !degrees 20
    MuonMomentum: !MuonMomentum
      min: !GeV 2
    Antineutrino: !IsAntineutrino
    DeadTime: !DeadDiscriminators
      max: 1
    ODEnergyLimit: !ODEnergyMax
      max: !MeV 250

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
#Backgrounds are well-constrained in the original (LE) inclusive 2D
#analysis.
sidebands:

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
  NeutralCurrent:
    NC: !IsNC
  WrongSignMuon:
    Antineutrino: !IsAntineutrino
