#!/usr/bin/env ProcessAnaTuples
#File: InclusivePzPT.yaml
#Brief: Reproduces Dan's Medium Energy port of Amy's Low Energy 2D
#       inclusive cross section in muon momentum components.  If I get
#       roughly the same answers, my event loop can't be too bad, right?
#Author: Andrew Olivier aolivier@ur.rochester.edu

model: *MnvGENIEv1

app:
  useNuEConstraint: true
  nFluxUniverses: 50

systematics: []

signal: !EAvailableResolution
  name: "EAvailable"
  variable:
  binning: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.2, 2.4, 2.6, 2.8, 3, 3.5, 4]

cuts:
  truth:
    phaseSpace:
      TrackAngle: &AngleCut !TrackAngle
        max: !degrees 20
      PZMu: !MuonZMomentum
        min: !GeV 1.5
      Tracker: &Fiducial !IsInTarget
        truth: &TruthFiducial
          min: !mm 5980
          max: !mm 8422
        reco: *TruthFiducial
      Apothem: &ApothemCut !Apothem
        apothem: !mm 850
    signal:
      Neutrino: !IsNeutrino
      CC: !IsCC
  reco:
    Tracker: *Fiducial
    TrackAngle: !TrackAngle
      max: !degrees 19.996227
    Neutrino: !IsNeutrino
    DeadTime: !DeadDiscriminators
      max: 1
    Apothem: *ApothemCut

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
#Backgrounds are well-constrained in the original (LE) inclusive 2D
#analysis.
sidebands:

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
  NeutralCurrent:
    NC: !IsNC
  WrongSignMuon:
    Antineutrino: !IsAntineutrino
