#!/usr/bin/env ProcessAnaTuples
#File: InclusivePzPT.yaml
#Brief: Reproduces Dan's Medium Energy port of Amy's Low Energy 2D
#       inclusive cross section in muon momentum components.  If I get
#       roughly the same answers, my event loop can't be too bad, right?
#Author: Andrew Olivier aolivier@ur.rochester.edu

model: *MnvGENIEv1

app:
  skipSystematics:
  AnaTupleName: &TupleName "CCQENu"
  HypothesisName: *TupleName
  nuPDG: 14
  useNuEConstraint: true

signal: !MuonPzPTSignal
  name: "MuonPzPT"
  variable: &Variable
    x:
      truth:
      reco:
    y:
      truth:
      reco:
  binning:
    x: &xBins [ 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 7, 8, 9, 10, 15, 20, 40, 60]
    y: &yBins [ 0, 0.075, 0.15, 0.25, 0.325, 0.4, 0.475, 0.55, 0.7, 0.85, 1, 1.25, 1.5, 2.5, 4.5]

cuts:
  truth:
    phaseSpace:
      TrackAngle: &AngleCut !TrackAngle
        max: !degrees 20
      PZMu: !MuonZMomentum
        min: !GeV 1.5
    signal:
      Tracker: &Fiducial !IsInTarget
        truth: &TruthFiducial
          min: !mm 5980
          max: !mm 8422
        reco: *TruthFiducial
      Neutrino: !IsNeutrino
      Apothem: &ApothemCut !Apothem
        apothem: !mm 850
      CC: !IsCC
  reco:
    #Tracker: *Fiducial
    TrackAngle: !TrackAngle
      max: !degrees 19.996227
    Neutrino: !IsNeutrino
    DeadTime: !DeadDiscriminators
      max: 1
    Apothem: *ApothemCut
    HasMuon: !HasInteractionVertex

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
#Backgrounds are well-constrained in the original (LE) inclusive 2D
#analysis.
sidebands:

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
  NeutralCurrent:
    NC: !IsNC
  WrongSignMuon:
    Antineutrino: !IsAntineutrino
