#!/usr/bin/env ProcessAnaTuples
#Example of how to define an analysis job for a single target.

app:
  #TODO: candidate algorithm and other such options

#TODO: Figure out how to configure cuts that define neutron candidates.
#      This is really more of a reconstruction step, but I have to do it
#      now for flexibility of cut decisions and systematics.
signal: !MuonMomentum
  name: "Muon Momentum"
  variable: &Variable
  binning: &bins [ 0, 0.1, 0.2, 0.5, 0.7, 1.2, 3 ]

cuts:
  truth:
    phaseSpace:
      MuonMomentum: !MuonMomentum
        min: !GeV 2
      TrackAngle: !TrackAngle
        max: !degrees 17 #stricter constraint for the targets
    signal:
      Antineutrino: !IsAntineutrino
      LowQ3: &Q3Range !Q3Range
        min: !GeV 0
        max: !GeV 0.4
      Target3:
        *OneTrackTarget3
      Iron: !Target3Iron
  reco:
    OneTrack: !nTracks
      max: 1
    LowQ3: *Q3Range
    MinosDeltaT: !MinosDeltaT
      max: !ns 20
    TrackAngle: !TrackAngle
      max: !degrees 17 #stricter constraint for the targets
    MuonMomentum: !MuonMomentum
      min: !GeV 2
    Antineutrino: !IsAntineutrino
    Target3:
      *OneTrackTarget3
    Iron: !Target3Iron

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
sidebands:
  UpstreamPlastic: !MuonMomentum
    variable: *Variable
    binning: *bins
    fails: [Target3]
    passes:
      Upstream: &USPlastic !Between
        us: *OneTrackTarget2
        ds: *OneTrackTarget3
  DownstreamPlastic: !MuonMomentum
    variable: *Variable
    binning: *bins
    fails: [Target3]
    passes:
      Downstream: &DSPlastic !Between
        us: *OneTrackTarget3
        ds: *OneTrackTarget4
  WrongMaterial: !MuonMomentum
    variable: *Variable
    binning: *bins
    fails: [Iron]
    #And implicitly passes the Target3 truth cut

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
  UpstreamPlastic:
    Upstream: *USPlastic
  DownstreamPlastic:
    Downstream: *DSPlastic
  Lead:
    IsInLead: !Target3Lead
  Carbon:
    IsInCarbon: !Target3Carbon
  Water:
    IsInWater: !Water
