#File: Targets.yaml
#Brief: Z ranges of MINERvA's nuclear targets in truth and reconstruction.
#       Reco cuts taken from Jeffrey's analysis in the Fall of 2019.
#       See here for Jeffrey's reco cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/target_cuts.cpp
#       Truth cuts taken from Jeffrey's analysis in January 2020.
#       See here for Jeffrey's truth cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/true_target_cuts.cpp
#       
#Author: Andrew Olivier aolivier@ur.rochester.edu

neutronCounter: &neutronCounter
  truth:
    MinKE: !MeV 10
  reco:
    MinEDep: !MeV 1.5 #Just above cross-talk
    MaxZDist: !mm 1500 #roughly tuned for tracker
    EDepBoxMin: !MeV 0
    DistBoxMax: !mm 10000
    Pi0RemovalCosineMin: 0
    Pi0RemovalCosineMax: 0.97
    #VertexBoxDist: !mm 50

OneTrack:
  "Target 1": &OneTrackTarget1 !IsInTarget 
    truth:
      min: !mm 4465
      max: !mm 4500
    reco:
      min: !mm 4500
      max: !mm 4520
  "Target 2": &OneTrackTarget2 !IsInTarget
    truth:
      min: !mm 4680
      max: !mm 4720
    reco:
      min: !mm 4720
      max: !mm 4740
  "Target 3": &OneTrackTarget3 !IsInTarget
    truth:
      min: !mm 4900
      max: !mm 4990 #TODO: Jeffrey has a smaller range for the other materials!  He uses 4950 when target Z is not 6.  Does this doom me to per-section z cuts?  I guess anything in the lead section (for example) between 4950 and 4990 is in air.  Decided to just check target Z for target 3 iron and lead.
    reco:
      min: !mm 4980
      max: !mm 5010
  "Water Target": &OneTrackWaterTarget !IsInTarget
    truth:
      min: !mm 5170
      max: !mm 5440
    reco:
      min: !mm 5450
      max: !mm 5460
  "Target 4": &OneTrackTarget4 !IsInTarget
    truth:
      min: !mm 5635
      max: !mm 5650
    reco:
      min: !mm 5660
      max: !mm 5690
  "Target 5": &OneTrackTarget5 !IsInTarget
    truth:
      min: !mm 5765
      max: !mm 5790
    reco:
      min: !mm 5800
      max: !mm 5820
  "Tracker": &OneTrackTracker !IsInTarget
    truth:
      min: !mm 5890
      max: !mm 8467
    reco:
      min: !mm 6000
      max: !mm 8500

MultiTrack:
  "Target 1": &MultiTrackTarget1 !IsInTarget
    truth:
      min: !mm 4465
      max: !mm 4500
    reco:
      min: !mm 4500
      max: !mm 4530
  "Target 2": &MultiTrackTarget2 !IsInTarget
    truth:
      min: !mm 4680
      max: !mm 4720
    reco:
      min: !mm 4685
      max: !mm 4730
  "Target 3": &MultiTrackTarget3 !IsInTarget
    truth:
      min: !mm 4900
      max: !mm 4990
    reco:
      min: !mm 4910
      max: !mm 4980
  "Water Target": &MultiTrackWaterTarget !IsInTarget
    truth:
      min: !mm 5170
      max: !mm 5440
    reco:
      min: !mm 5200
      max: !mm 5420
  "Target 4": &MultiTrackTarget4 !IsInTarget
    truth:
      min: !mm 5635
      max: !mm 5650
    reco:
      min: !mm 5635
      max: !mm 5660
  "Target 5": &MultiTrackTarget5 !IsInTarget
    truth:
      min: !mm 5765
      max: !mm 5790
    reco:
      min: !mm 5760
      max: !mm 5795
  "Tracker": &MultiTrackTracker !IsInTracker
    truth:
      min: !mm 5890
      max: !mm 8467
    reco:
      min: !mm 6000
      max: !mm 8500
#!/usr/bin/env ProcessAnaTuples
#File: NucCCNeutronsAntineutrinoStandard.yaml
#Brief: My standard cuts for my neutron multiplicity analysis in antineutrino mode in the TRACKER.
#       You still have to plug in a "signal" block and a systematics block from another YAML file
#       on the command line.
#Author: Andrew Olivier aolivier@ur.rochester.edu

#MnvGENIEv1
model:
  Flux: !FluxAndCV
  GENIE: !GENIEPionTunes
    useNonResPi: true
    useDeuteriumPionTune: false
  MINOSEfficiency: !MINOSEfficiency
  RPASuppression: !RPA
  Valencia2p2h: !LowRecoil2p2hWeight
  AbfaltererNeutronInelastic: !GeantNeutronCV

#nu-e constraint doesn't work in antineutrino data yet as of 6/4/2020.
#100 flux universes matches the NSF validation suite.
app:
  useNuEConstraint: false
  nFluxUniverses: 100

fiducials:
  Tracker: !Tracker
    zRange: *OneTrackTracker
    apothem:
      apothem: !mm 850

#Basically, Amy/Dan's inclusive Cuts (adapted for my AnaTool) + available energy.
cuts:
  truth:
    phaseSpace:
      MuonMomentum: !MuonMomentum
        min: !GeV 2
        max: !GeV 20
      TrackAngle: !TrackAngle
        max: !degrees 20
    signal:
      LowEAvailable: &EAvailCut !EAvailRange
        min: &smallNegativeNumber !GeV -1 #-1e-3
        max: &maxEAvail !MeV 100
      ManyNeutrons: &ManyNeutrons !NeutronMultiplicity
        min: !neutrons 2
        #max: !neutrons 3
        variable: *neutronCounter
      Antineutrino: !IsAntineutrino
      CC: !IsCC
  reco:
    LowEAvailable: !RecoilERange
      min: *smallNegativeNumber
      max: *maxEAvail
      EAvailable: *neutronCounter
    ManyNeutrons: *ManyNeutrons
    #Pi0DirectionCut: !NoPi0Candidates #TODO: Make this part of candidate definition so that candidates that are pi0-like have their energy included in EAvail
    #  neutronCounter: *neutronCounter
    #  blobAngleMin: 0.45
    #  blobAngleMax: 0.95
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: !degrees 20
    MuonMomentum: !MuonMomentum
      min: !GeV 2
      max: !GeV 20
    Antineutrino: !IsAntineutrino
    DeadTime: !DeadDiscriminators
      max: 1
backgrounds:
  #NeutralCurrent:
  #  NC: !IsNC
  #WrongSignMuon:
  #  Neutrino: !IsNeutrino
  ChargedPions:
    NoPi0s: !NoPi0s
    HasChargedPions: &hasChargedPions !ChargedHadronMultiplicity
      equals: 1
      angleThrshold: &angleThreshold !degrees 90
      trackingThresholds: &pionThresholds
        211: !MeV 35
        -211: !MeV 35
  NeutralPionsOnly:
    NoChargedPions: &noChargedPions !ChargedHadronMultiplicity
      equals: 0
      angleThreshold: *angleThreshold
      trackingThresholds: *pionThresholds
    HasPi0s: &hasPi0s !ChargedHadronMultiplicity
      equals: 1
      angleThreshold: !degrees 90
      trackingThresholds:
        111: !MeV 0
  MultiPi:
    HasMultiPions: !ChargedHadronMultiplicity
      min: 2
      angleThrshold: &angleThreshold !degrees 90
      trackingThresholds: &pionThresholds
        211: !MeV 35
        -211: !MeV 35
        111: !MeV 0
  "1 Neutron":
    LowEAvail: *EAvailCut
    Antineutrino: !IsAntineutrino
    CC: !IsCC
    SingleNeutron: !NeutronMultiplicity
      equals: !neutrons 1
      variable: *neutronCounter
  "0 Neutrons":
    LowEAvail: *EAvailCut
    Antineutrino: !IsAntineutrino
    CC: !IsCC
    NoNeutrons: !NeutronMultiplicity
      equals: !neutrons 0
      variable: *neutronCounter
  ProtonsAboveAmitsThresholdOnly:
    NoPi0s: !NoPi0s
    NoChargedPions: *noChargedPions
    HasProtons: !ChargedHadronMultiplicity &hasProtons
      min: 1
      angleThreshold: *angleThreshold
      trackingThresholds:
        2212: !MeV 120
  #TooManyNeutrons:
  #  NoPi0s: !NoPi0s
  #  NoChargedHadrons: *NoChargedHadrons
  #  ManyNeutrons: !NeutronMultiplicity
  #    min: !neutrons 4
  #    variable: *neutronCounter
signal: !MuonPTSignal
  name: "MuonPTSignal"
  variable:
  binning: &pTBins [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.5, 2.0, 2.5]
 
sidebands:
  Pi0: !MuonPTSideband
    name: "Pi0"
    fails: ["LowEAvailable"]
    passes:
      #A looser available energy cut to clamp down on multi-pi events
      LowEAvailable: !RecoilERange
        min: *smallNegativeNumber
        max: &EAvailForPions !MeV 200
        EAvailable: *neutronCounter
      Pi0DirectionCut: !HasPi0Candidate
        neutronCounter: *neutronCounter
        blobAngleMin: 0.95
      AtLeast3Candidates: !NeutronMultiplicity
        min: !neutrons 3
        variable: *neutronCounter
      NoHadronTracks: !nTracks
        max: 1
    variable:
    binning: *pTBins
  ChargedHadrons: !MuonPTSideband
    name: "Charged Hadrons"
    fails: ["LowEAvailable"]
    passes:
      #A looser available energy cut to clamp down on multi-pi events
      LowEAvailable: !RecoilERange
        min: *smallNegativeNumber
        max: *EAvailForPions
        EAvailable: *neutronCounter
      HasHadronTracks: !nTracks
        min: 2
      Pi0DirectionCut: !NoPi0Candidates
        neutronCounter: *neutronCounter
        blobAngleMin: 0.45
        blobAngleMax: 0.95
    variable:
    binning: *pTBins
  #TODO: I want to require either 2 pi0s, 2 charged pions, or one of each
  MultiPi: !MuonPTSideband
    name: "Multiple Pions"
    fails: ["LowEAvailable"]
    passes:
      LowEAvailable: !RecoilERange
        min: *smallNegativeNumber
        max: *EAvailForPions
        EAvailable: *neutronCounter
      HasHadronTracks: !nTracks
        min: 2
      Pi0DirectionCut: !HasPi0Candidate
        neutronCounter: *neutronCounter
        blobAngleMin: 0.95
      AtLeast3Candidates: !NeutronMultiplicity
        min: !neutrons 3
        variable: *neutronCounter
    variable:
    binning: *pTBins
  QELike: !MuonPTSideband
    name: "QELike"
    fails: ["ManyNeutrons"]
    passes:
      UpToOneCandidate: !NeutronMultiplicity
        max: !neutrons 1
        variable: *neutronCounter
      Pi0DirectionCut: !NoPi0Candidates
        neutronCounter: *neutronCounter
        blobAngleMin: 0.45
        blobAngleMax: 0.95
      NoHadronTracks: !nTracks
        max: 1
    variable:
    binning: *pTBins
  #ManyNeutrons: !MuonPTSideband
  #  name: "ManyNeutrons"
  #  fails: ["ManyNeutrons"]
  #  passes:
  #    ManyCandidates: !NeutronMultiplicity
  #      min: !neutrons 3
  #      variable: *neutronCounter
  #  variable:
  #  binning: *pTBins
