neutronCounter: &neutronCounter
  truth:
    MinKE: !MeV 10
  reco:
    MinEDep: !MeV 1.5 #Just above cross-talk
    MaxZDist: !mm 1500 #roughly tuned for tracker
    EDepBoxMin: !MeV 0
    DistBoxMax: !mm 10000
    #VertexBoxDist: !mm 50

#MnvTunev1
model:
  Flux: !FluxAndCV
  GENIE: !GENIEPionTunes
    useNonResPi: true
    useDeuteriumPionTune: false
  MINOSEfficiency: !MINOSEfficiency
  RPASuppression: !RPA
  Valencia2p2h: !LowRecoil2p2hWeight
    mode: 0
  AbfaltererNeutronInelastic: !GeantNeutronCV
  FSIBugFix: !FixFSIBugGENIE
    useElastic: true
    useAbsorption: false

systematics:
  #Analysis-specific systematics
  MoNANeutronInelastic: !MoNANeutronInelastic
    nGamma: [1000060120, 2112]
    threeAlpha: [1000020040, 1000020040, 1000020040, 2112]
    Bnp: [1000050110, 2112, 2212]
  #Beam angle
  BeamAngleX:
  BeamAngleY:
  #Flux
  Flux:
  #Genie knobs
  GENIE_AGKYxF1pi:
  GENIE_AhtBY:
  GENIE_BhtBY:
  GENIE_CCQEPauliSupViaKF:
  GENIE_CV1uBY:
  GENIE_CV2uBY:
  GENIE_EtaNCEL:
  GENIE_FrAbs_N:
  GENIE_FrAbs_pi:
  GENIE_FrCEx_N:
  GENIE_FrCEx_pi:
  #GENIE_FrElas_N: #Not relevant and broken when the FSI bug fix weight is used
  GENIE_FrElas_pi:
  GENIE_FrInel_N:
  GENIE_FrPiProd_N:
  GENIE_FrPiProd_pi:
  GENIE_MFP_N:
  GENIE_MFP_pi:
  #GENIE_MaCCQEshape
  GENIE_MaNCEL:
  GENIE_MaRES:
  GENIE_MvRES:
  #GENIE_NormCCQE
  #GENIE_NormCCRES
  GENIE_NormDISCC:
  GENIE_NormNCRES:
  GENIE_RDecBR1gamma:
  GENIE_Rvn1pi:
  GENIE_Rvp1pi:
  GENIE_Rvn2pi:
  GENIE_Rvp2pi:
  GENIE_Theta_Delta2Npi:
  GENIE_VecFFCCQEshape:
  #Minos Reconstruction
  MINOS_Reconstruction_Efficiency:
  #MINERvA tune systematics.  You might be able to turn some of these off
  #depending on your model block.
  Low_Recoil_2p2h_Tune:
  RPA_HighQ2:
  RPA_LowQ2:
  LowQ2Pi: #TODO: Broken?
  #Muon reconstruction
  Muon_Energy_Resolution:
  Muon_Energy_MINERvA:
  Muon_Energy_MINOS:
  MuonAngleXResolution:
  MuonAngleYResolution:
  #GEANT cross sections
  GEANT_Proton:
  GEANT_Neutron:
  GEANT_Pion:
  #Recoil energy
  response_proton:
  response_meson:
  response_em:
  response_other:
  #Target mass
  Target_Mass_CH:
  #Target_Mass_C:
  #Target_Mass_Fe
  #Target_Mass_Pb

#500 flux universes because no one ever did the study to prove that 100 is sufficient for RHC
app:
  useNuEConstraint: true
  nFluxUniverses: 500

fiducials:
  Tracker: !Tracker
    zRange:
      truth:
        min: !mm 5890
        max: !mm 8467
      reco:
        min: !mm 6000
        max: !mm 8500
    apothem:
      apothem: !mm 850

cuts:
  truth:
    phaseSpace:
      MuonMomentum: !MuonMomentum
        min: !GeV 2.0
        max: !GeV 20
      TrackAngle: !TrackAngle
        max: !degrees 20
    signal:
      LowEAvailable: &EAvailCut !EAvailRange
        min: &smallNegativeNumber !GeV -1
        max: &maxEAvail !MeV 100
      ManyNeutrons: &ManyNeutrons !NeutronMultiplicity
        min: !neutrons 2
        variable: *neutronCounter
      Antineutrino: !IsAntineutrino
      CC: !IsCC
  reco:
    LowEAvailable: !RecoilERange
      min: *smallNegativeNumber
      max: *maxEAvail
      EAvailable: *neutronCounter
    ManyNeutrons: *ManyNeutrons
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: !degrees 20
    MuonMomentum: !MuonMomentum
      min: !GeV 2.0
      max: !GeV 20
    Antineutrino: !IsAntineutrino
    DeadTime: !DeadDiscriminators
      max: 1

backgrounds:
  "1 Neutron":
    LowEAvail: *EAvailCut
    Antineutrino: !IsAntineutrino
    CC: !IsCC
    SingleNeutron: !NeutronMultiplicity
      equals: !neutrons 1
      variable: *neutronCounter
  "0 Neutrons":
    LowEAvail: *EAvailCut
    Antineutrino: !IsAntineutrino
    CC: !IsCC
    NoNeutrons: !NeutronMultiplicity
      equals: !neutrons 0
      variable: *neutronCounter
  HighEAvail:
    HighEAvailable: &EAvailCut !EAvailRange
      min: *maxEAvail
      max: !GeV 100

signal: !MuonPTSignal
  name: "MuonPTSignal"
  variable:
  binning: &pTBins [0, 0.05, 0.11, 0.17, 0.24, 0.31, 0.4, 0.5, 0.62, 0.77, 0.95, 1.18, 1.5] 
sidebands:
  HighEAvail: !MuonPTSideband
    name: "HighEAvail"
    fails: ["LowEAvailable"]
    passes:
      HighEAvailable: !RecoilERange
        min: *maxEAvail
        max: !MeV 200
        EAvailable: *neutronCounter
    variable:
    binning: *pTBins
  QELike: !MuonPTSideband
    name: "QELike"
    fails: ["ManyNeutrons"]
    passes:
      UpToOneCandidate: !NeutronMultiplicity
        max: !neutrons 1
        variable: *neutronCounter
    variable:
    binning: *pTBins
