#!/usr/bin/env ProcessAnaTuples
#File: Targets.yaml
#Brief: Z ranges of MINERvA's nuclear targets in truth and reconstruction.
#       Reco cuts taken from Jeffrey's analysis in the Fall of 2019.
#       See here for Jeffrey's reco cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/target_cuts.cpp
#       Truth cuts taken from Jeffrey's analysis in January 2020.
#       See here for Jeffrey's truth cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/true_target_cuts.cpp
#       
#Author: Andrew Olivier aolivier@ur.rochester.edu

app:
  #TODO: candidate algorithm and other such options

#TODO: Figure out how to configure cuts that define neutron candidates.
#      This is really more of a reconstruction step, but I have to do it
#      now for flexibility of cut decisions and systematics.
signal: !NeutronDetection
  name: "Neutron Detection"
  variable: &Variable
    truth:
      MinEDep: !MeV 10 #Not many detectable candidates below this threshold
    reco:
      MinEDep: !MeV 1.5 #Just above cross-talk
      MaxZDist: !mm 1500 #roughly tuned for tracker
  binning:
    edep: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]
    angle: [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
    beta: [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
    energy: [10, 12, 14, 16, 18, 20, 23, 26, 30, 35, 40, 45, 50, 55, 60, 65, 70, 85, 100, 150]

cuts:
  truth:
    phaseSpace:
      MuonMomentum: !MuonMomentum
        min: !GeV 2
      TrackAngle: !TrackAngle
        max: 20 #degrees; stricter constraint for the targets
    signal:
      Antineutrino: !IsAntineutrino
      LowQ3: &Q3Range !Q3Range
        max: !GeV 0.4
      Apothem: &ApothemCut !Apothem
        apothem: !mm 850
      Tracker: *OneTrackTracker
  reco:
    OneTrack: !nTracks
      max: 1
    LowQ3: &Q3Range !Q3Range
        max: !GeV 0.4
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: 20 #degrees; stricter constraint for the targets
    MuonMomentum: !MuonMomentum
      min: !GeV 2
    Antineutrino: !IsAntineutrino
    Apothem: *ApothemCut
    Tracker: *OneTrackTracker

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
sidebands:

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
