#File: CVOnly.yaml
#Brief: Use this file to turn off systematics when you're only interested 
#       in the CV.  It might decrease wall time by a factor of 5 when running
#       the same job multiple times.  Good for debugging.
#Author: Andrew Olivier aolivier@ur.rochester.edu

#File: Targets.yaml
#Brief: Z ranges of MINERvA's nuclear targets in truth and reconstruction.
#       Reco cuts taken from Jeffrey's analysis in the Fall of 2019.
#       See here for Jeffrey's reco cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/target_cuts.cpp
#       Truth cuts taken from Jeffrey's analysis in January 2020.
#       See here for Jeffrey's truth cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/true_target_cuts.cpp
#       
#Author: Andrew Olivier aolivier@ur.rochester.edu

OneTrack:
  "Target 1": &OneTrackTarget1 !IsInTarget 
    truth:
      min: !mm 4465
      max: !mm 4500
    reco:
      min: !mm 4500
      max: !mm 4520
  "Target 2": &OneTrackTarget2 !IsInTarget
    truth:
      min: !mm 4680
      max: !mm 4720
    reco:
      min: !mm 4720
      max: !mm 4740
  "Target 3": &OneTrackTarget3 !IsInTarget
    truth:
      min: !mm 4900
      max: !mm 4990 #TODO: Jeffrey has a smaller range for the other materials!  He uses 4950 when target Z is not 6.  Does this doom me to per-section z cuts?  I guess anything in the lead section (for example) between 4950 and 4990 is in air.  Decided to just check target Z for target 3 iron and lead.
    reco:
      min: !mm 4980
      max: !mm 5010
  "Water Target": &OneTrackWaterTarget !IsInTarget
    truth:
      min: !mm 5170
      max: !mm 5440
    reco:
      min: !mm 5450
      max: !mm 5460
  "Target 4": &OneTrackTarget4 !IsInTarget
    truth:
      min: !mm 5635
      max: !mm 5650
    reco:
      min: !mm 5660
      max: !mm 5690
  "Target 5": &OneTrackTarget5 !IsInTarget
    truth:
      min: !mm 5765
      max: !mm 5790
    reco:
      min: !mm 5800
      max: !mm 5820
  "Tracker": &OneTrackTracker !IsInTarget
    truth:
      min: !mm 5890
      max: !mm 8467
    reco:
      min: !mm 6000
      max: !mm 8500

MultiTrack:
  "Target 1": &MultiTrackTarget1 !IsInTarget
    truth:
      min: !mm 4465
      max: !mm 4500
    reco:
      min: !mm 4500
      max: !mm 4530
  "Target 2": &MultiTrackTarget2 !IsInTarget
    truth:
      min: !mm 4680
      max: !mm 4720
    reco:
      min: !mm 4685
      max: !mm 4730
  "Target 3": &MultiTrackTarget3 !IsInTarget
    truth:
      min: !mm 4900
      max: !mm 4990
    reco:
      min: !mm 4910
      max: !mm 4980
  "Water Target": &MultiTrackWaterTarget !IsInTarget
    truth:
      min: !mm 5170
      max: !mm 5440
    reco:
      min: !mm 5200
      max: !mm 5420
  "Target 4": &MultiTrackTarget4 !IsInTarget
    truth:
      min: !mm 5635
      max: !mm 5650
    reco:
      min: !mm 5635
      max: !mm 5660
  "Target 5": &MultiTrackTarget5 !IsInTarget
    truth:
      min: !mm 5765
      max: !mm 5790
    reco:
      min: !mm 5760
      max: !mm 5795
  "Tracker": &MultiTrackTracker !IsInTracker
    truth:
      min: !mm 5890
      max: !mm 8467
    reco:
      min: !mm 6000
      max: !mm 8500

#MnvGENIEv1
model:
  Flux: !FluxAndCV
  GENIE: !GENIEPionTunes
    useNonResPi: true
    useDeuteriumPionTune: false
  MINOSEfficiency: !MINOSEfficiency
  RPASuppression: !RPA
  Valencia2p2h: !LowRecoil2p2hWeight
  AbfaltererNeutronInelastic: !GeantNeutronCV
    FSIBugFix: !FixFSIBugGENIE
    useElastic: true
    useAbsorption: false

#nu-e constraint doesn't work in antineutrino data yet as of 6/4/2020.
#100 flux universes matches the NSF validation suite.
app:
  useNuEConstraint: true
  nFluxUniverses: 100

fiducials:
  Tracker: !Tracker
    zRange: *OneTrackTracker
    apothem:
      apothem: !mm 850


neutronCounter: &neutronCounter
  truth:
    MinKE: !MeV 10
  reco:
    MinEDep: !MeV 1.5 #Just above cross-talk
    MaxZDist: !mm 1500 #roughly tuned for tracker
    EDepBoxMin: !MeV 0
    DistBoxMax: !mm 10000
    Pi0RemovalCosineMin: 0
    Pi0RemovalCosineMax: 0.97

#Basically, Amy/Dan's inclusive Cuts (adapted for my AnaTool) + available energy.
cuts:
  truth:
    phaseSpace:
      #LowQ3: &q3Cut !Q3Range
      #  min: !MeV 0
      #  max: !MeV 400
      #  caloTune: "NukeCC_AntiNu_Tracker"
      #MuonMomentum: !MuonMomentum
      #  min: !GeV 2
      #  max: !GeV 20
      #TrackAngle: !TrackAngle
      #  max: !degrees 20
    #signal:
      #Antineutrino: !IsAntineutrino
      #CC: !IsCC
  reco:
    MidQ3: !Q3Range
      min: !MeV 400
      max: !MeV 800
      caloTune: "NukeCC_AntiNu_Tracker"
    OneTrack: !nTracks
      max: 1
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: !degrees 20
    MuonMomentum: !MuonMomentum
      min: !GeV 2
      max: !GeV 20
    Antineutrino: !IsAntineutrino
    DeadTime: !DeadDiscriminators
      max: 1

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
#None yet!
sidebands:

#TODO: I'll want these some day
backgrounds:
#  NeutralCurrent:
#    NC: !IsNC
#  WrongSignMuon:
#    Antineutrino: !IsAntineutrino

#!/usr/bin/env ProcessAnaTuples
#File: NeutronDetection_StudyOnly.yaml
#Brief: Study neutron detection efficiency and sources of backgrounds.  Needs to
#       be used with a selection definition and a list of systematics.
#Author: Andrew Olivier aolivier@ur.rochester.edu
signal: !NeutronDetection
  name: "Neutron Detection"
  variable: *neutronCounter
  binning:
    edep: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]
    angle: [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
    beta: [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
    energy: [10, 12, 14, 16, 18, 20, 23, 26, 30, 35, 40, 45, 50, 55, 60, 65, 70, 85, 100, 150]
    zDist: [0, 30, 60, 90, 150, 300, 450, 600, 800, 1000, 1250, 1500]
