#!/usr/bin/env ProcessAnaTuples
#File: Targets.yaml
#Brief: Z ranges of MINERvA's nuclear targets in truth and reconstruction.
#       Reco cuts taken from Jeffrey's analysis in the Fall of 2019.
#       See here for Jeffrey's reco cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/target_cuts.cpp
#       Truth cuts taken from Jeffrey's analysis in January 2020.
#       See here for Jeffrey's truth cuts: https://cdcvs.fnal.gov/redmine/projects/minerva-sw/repository/entry/AnalysisFramework/Ana/NukeCCQE/scripts/code_templates/true_target_cuts.cpp
#       
#Author: Andrew Olivier aolivier@ur.rochester.edu

model: *MnvGENIEv1

app:
  useNuEConstraint: false
  nFluxUniverses: 100


#TODO: Figure out how to configure cuts that define neutron candidates.
#      This is really more of a reconstruction step, but I have to do it
#      now for flexibility of cut decisions and systematics.
signal: !NeutronMultiplicitySignal
  name: "Neutron Multiplicity"
  variable: &Variable
    truth:
      MinKE: !MeV 10 #Not many detectable candidates below this threshold
    reco:
      MinEDep: !MeV 1.5 #Just above cross-talk
      MaxZDist: !mm 1500 #roughly tuned for tracker
  binning: &bins [ 0, 1, 2, 4, 10] #TODO: Accept any number of neutrons in last bin and label as > 4 

cuts:
  truth:
    phaseSpace:
      Apothem: !Apothem
        apothem: !mm 850
      Tracker: *OneTrackTracker
      MuonMomentum: !MuonMomentum
        min: !GeV 2
      TrackAngle: !TrackAngle
        max: !degrees 20
      LowEAvailable: !EAvailRange
        min: &smallNegativeNumber !GeV -1e-3
        max: &maxEAvail !GeV 0.1
    signal:
      Antineutrino: !IsAntineutrino
      CC: !IsCC
  reco:
    Apothem: !Apothem
      apothem: !mm 850
    Tracker: *OneTrackTracker
    LowEAvailable: !RecoilERange
        min: *smallNegativeNumber
        max: *maxEAvail
    MinosDeltaT: !MinosDeltaT
      min: !ns -40
      max: !ns 110
    TrackAngle: !TrackAngle
      max: !degrees 20
    MuonMomentum: !MuonMomentum
      min: !GeV 2
    Antineutrino: !IsAntineutrino
    DeadTime: !DeadDiscriminators
      max: 1

#Names in sidebands' "fails" blocks refer to truth cuts by block name.
sidebands:

#Backgrounds are defined by the truth::Cuts they pass in addition to
#failing some regular truth cut.  So, these cuts had better be mutually
#exclusive with regular truth::Cuts.
backgrounds:
